### ISSUE TITLE
Правки до ДЗ 22

### ISSUE THREAD

**Issue by Dexter19** [IgorBill/IgorBill.github.io#1]
1.Отримати всі елементи з тегом h1. Вивести на консоль тип отриманого об'єкту та його розмір. Використовуючи цикл for, вивести на консоль кожний елемент з отриманого об'єкту
Ви використали цикл for of для вирішення цього завдання. Все добре, але в завданні умовою є вивести циклом for.
for (let i = 0; i < allTitles.length; i++) {
...your code
}
Аналогічно зробіть у 6 та 7 завданні.
------------------------------

**Comment by IgorBill** [comment]
Правки до ДЗ 22 виправлено
