### ISSUE TITLE
Правки до ДЗ 28

### ISSUE THREAD

**Issue by Dexter19** [IgorBill/IgorBill.github.io#3]
У вашому регулярному виразі для перевірки пароля ви використовуєте [0-9a-zA-Z!@#$%^&*], що означає "будь-який символ, який є буквою (великою або маленькою), цифрою або спеціальним символом". Проте ви забули вказати кількість символів, що повторюються. Потрібно додати + в квадратні дужки, щоб вказати, що один або більше символів можуть повторюватися. Отже, поправлений регулярний вираз буде виглядати так: /(?=.*[0-9])(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*]+/.
У вас код для відображення попередження про успішну реєстрацію (alert('Реєстраці пройшла успішно');) знаходиться після виклику registrationForm.submit();. Це не дозволить йому відображатися, оскільки відправка форми перенаправить сторінку, і код після неї не виконається. Тому, краще спочатку відобразити попередження, а потім викликати registrationForm.submit();.

**Comment by IgorBill** [comment]
Виправив, дякую
